from cea import CEAException


class CEAAuthError(CEAException):
    """Raised when there is an error with the authentication"""
    pass
